export const config = {
	port: Number(process.env.PORT) || 3000,
	dev: process.env.NODE_ENV !== "production",
	logLevel: process.env.LOG_LEVEL || "info",
	encryptionAlgo: process.env.ENCRYPTION_ALGO || "aes-256-cbc",
	encryptionKey: process.env.ENCRYPTION_KEY || "torrent_stream_default_key",
	streamMemoryLimit:
		Number(process.env.STREAM_MEMORY_LIMIT) || 128 * 1024 * 1024,
	torrentAddTimeout: Number(process.env.TORRENT_ADD_TIMEOUT) || 5 * 1000,
	torrentIdleTimeout: Number(process.env.TORRENT_IDLE_TIMEOUT) || 60 * 1000,
	torrentRemoveTimeout:
		Number(process.env.TORRENT_REMOVE_TIMEOUT) || 5 * 60 * 1000,
	torrentProviders: process.env.TORRENT_PROVIDERS?.split(",") ?? [],
	torrentFormats: process.env.TORRENT_FORMATS?.split(",") ?? [
		"4k",
		"1080p",
		"720p",
		"dv",
		"hdr",
		"uhdbluray",
		"bluray",
		"remux",
		"web",
		"dvd",
		"hdtv",
		"sdtv",
		"screener",
		"cam",
		"3d",
		"unknown",
		"av1",
		"hevc",
		"avc",
		"divx",
		"xvid",
	],
	torrentLanguages: process.env.TORRENT_LANGUAGES?.split(",") ?? [],
	webRequestTimeout: Number(process.env.WEB_REQUEST_TIMEOUT) || 5 * 1000,
	ncoreUser: process.env.NCORE_USER,
	ncorePass: process.env.NCORE_PASS,
	insaneUser: process.env.INSANE_USER,
	insanePass: process.env.INSANE_PASS,
};
